[profile.default]
solc = '0.8.23'
evm_version = 'paris'

src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [
  { access = "read", path = "./out"},
  { access = "read", path = "./.release-tmp"}
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config